/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ShoeHealth = IDL.Record({
  'id' : IDL.Text,
  'lastMaintained' : IDL.Nat,
  'wear' : IDL.Nat,
  'steps' : IDL.Nat,
  'style' : IDL.Text,
  'performance' : IDL.Nat,
  'brand' : IDL.Text,
});
export const ShoeCategory = IDL.Variant({
  'sneakers' : IDL.Null,
  'customDesigns' : IDL.Null,
  'sportsShoes' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ShoeProduct = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'style' : IDL.Text,
  'details' : IDL.Text,
  'category' : ShoeCategory,
  'brand' : IDL.Text,
  'image' : ExternalBlob,
  'isNFT' : IDL.Bool,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NFT = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'metadata' : IDL.Text,
  'name' : IDL.Text,
  'image' : ExternalBlob,
});
export const AirIntegrationSettings = IDL.Record({
  'enabledOledSync' : IDL.Bool,
  'enabledShoeHealth' : IDL.Bool,
  'enabledShoeMusic' : IDL.Bool,
});
export const AudioUsageContext = IDL.Variant({
  'soundEffect' : IDL.Null,
  'vrExperience' : IDL.Null,
  'other' : IDL.Null,
  'post' : IDL.Null,
  'narration' : IDL.Null,
  'xrExperience' : IDL.Null,
  'ambientSound' : IDL.Null,
  'backgroundMusic' : IDL.Null,
  'avatar' : IDL.Null,
});
export const AudioType = IDL.Variant({
  'ambient' : IDL.Null,
  'music' : IDL.Null,
  'soundEffect' : IDL.Null,
  'voiceRecording' : IDL.Null,
  'other' : IDL.Null,
  'podcast' : IDL.Null,
  'audiobook' : IDL.Null,
});
export const AudioAttachment = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'usageContext' : AudioUsageContext,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'audioFile' : ExternalBlob,
  'audioType' : AudioType,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const ChatThread = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'messages' : IDL.Vec(Message),
  'lastMessage' : IDL.Opt(Message),
});
export const VRExperience = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'audioAttachments' : IDL.Vec(AudioAttachment),
  'image' : IDL.Opt(ExternalBlob),
});
export const PortfolioContent = IDL.Record({
  'vrExperiences' : IDL.Vec(VRExperience),
  'nfts' : IDL.Vec(NFT),
  'posts' : IDL.Vec(Post),
});
export const DashboardMetrics = IDL.Record({
  'revenue' : IDL.Nat,
  'engagementRate' : IDL.Nat,
  'salesPerformance' : IDL.Nat,
  'followers' : IDL.Nat,
});
export const PublicUserProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Theme = IDL.Variant({
  'dark' : IDL.Null,
  'neon' : IDL.Null,
  'light' : IDL.Null,
});
export const DashboardLayout = IDL.Record({
  'analyticsSection' : IDL.Text,
  'postSection' : IDL.Text,
  'nftSection' : IDL.Text,
  'vrSection' : IDL.Text,
});
export const MonetizationConfig = IDL.Record({
  'theme' : Theme,
  'exclusiveContentEnabled' : IDL.Bool,
  'tipsEnabled' : IDL.Bool,
  'nftDropsEnabled' : IDL.Bool,
  'dashboardLayout' : DashboardLayout,
});
export const CreatorMonetizationDashboard = IDL.Record({
  'content' : PortfolioContent,
  'metrics' : DashboardMetrics,
  'userProfile' : PublicUserProfile,
  'config' : MonetizationConfig,
});
export const DesignFileType = IDL.Variant({
  'image2D' : IDL.Null,
  'model3D' : IDL.Null,
});
export const DesignFile = IDL.Record({
  'id' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'blob' : ExternalBlob,
  'fileType' : DesignFileType,
});
export const DesignCustomization = IDL.Record({
  'effects' : IDL.Vec(IDL.Text),
  'patterns' : IDL.Vec(IDL.Text),
  'textures' : IDL.Vec(IDL.Text),
  'colors' : IDL.Vec(IDL.Text),
});
export const ShoeDesignProject = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'designFiles' : IDL.Vec(DesignFile),
  'customization' : DesignCustomization,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const FriendRequest = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'status' : RequestStatus,
  'from' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const LiveEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'thumbnail' : IDL.Opt(ExternalBlob),
  'votes' : IDL.Nat,
  'hostName' : IDL.Text,
  'host' : IDL.Principal,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'participantCount' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'liveEvent' : IDL.Null,
  'like' : IDL.Null,
  'shoeHealthAlert' : IDL.Null,
  'comment' : IDL.Null,
  'nftDrop' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'notificationType' : NotificationType,
  'user' : IDL.Principal,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const OLEDSettings = IDL.Record({
  'bluetoothPaired' : IDL.Bool,
  'displayMode' : IDL.Text,
  'enabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Nat], [], []),
  'addOrUpdateShoeHealth' : IDL.Func([ShoeHealth], [], []),
  'addShoeProduct' : IDL.Func([ShoeProduct], [], []),
  'addShoeStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatThread' : IDL.Func([IDL.Vec(IDL.Principal)], [IDL.Nat], []),
  'createDesignProject' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createLiveEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'createNFT' : IDL.Func([NFT], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [IDL.Nat], []),
  'createPostWithAudio' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteAudioAttachment' : IDL.Func([IDL.Text], [], []),
  'deleteDesignProject' : IDL.Func([IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAirIntegrationSettings' : IDL.Func(
      [IDL.Text],
      [AirIntegrationSettings],
      ['query'],
    ),
  'getAllAudioAttachments' : IDL.Func(
      [],
      [IDL.Vec(AudioAttachment)],
      ['query'],
    ),
  'getAllPostsAudioIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getAllShoeProducts' : IDL.Func([], [IDL.Vec(ShoeProduct)], ['query']),
  'getAudioAttachment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AudioAttachment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatThreads' : IDL.Func([], [IDL.Vec(ChatThread)], ['query']),
  'getCreatorDashboard' : IDL.Func(
      [],
      [IDL.Opt(CreatorMonetizationDashboard)],
      ['query'],
    ),
  'getDesignProject' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ShoeDesignProject)],
      ['query'],
    ),
  'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
  'getLiveEvents' : IDL.Func([], [IDL.Vec(LiveEvent)], ['query']),
  'getMonetizationConfig' : IDL.Func(
      [],
      [IDL.Opt(MonetizationConfig)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOLEDSettings' : IDL.Func([], [IDL.Opt(OLEDSettings)], ['query']),
  'getPostAudioIds' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getShoeProduct' : IDL.Func([IDL.Text], [IDL.Opt(ShoeProduct)], ['query']),
  'getShoeProductsByCategory' : IDL.Func(
      [ShoeCategory],
      [IDL.Vec(ShoeProduct)],
      ['query'],
    ),
  'getShoeStockCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserDesignProjects' : IDL.Func(
      [],
      [IDL.Vec(ShoeDesignProject)],
      ['query'],
    ),
  'getUserNFTs' : IDL.Func([IDL.Principal], [IDL.Vec(NFT)], ['query']),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserShoeHealth' : IDL.Func([], [IDL.Vec(ShoeHealth)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinLiveEvent' : IDL.Func([IDL.Nat], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'rejectFriendRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMonetizationConfig' : IDL.Func([MonetizationConfig], [], []),
  'saveOLEDSettings' : IDL.Func([OLEDSettings], [], []),
  'searchShoeProducts' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Principal)],
      [IDL.Vec(ShoeProduct)],
      ['query'],
    ),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'updateAirIntegrationSettings' : IDL.Func(
      [IDL.Text, AirIntegrationSettings],
      [],
      [],
    ),
  'updateDesignCustomization' : IDL.Func(
      [IDL.Text, DesignCustomization],
      [],
      [],
    ),
  'uploadAudioAttachment' : IDL.Func([AudioAttachment], [], []),
  'uploadDesignFile' : IDL.Func(
      [IDL.Text, DesignFileType, ExternalBlob, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ShoeHealth = IDL.Record({
    'id' : IDL.Text,
    'lastMaintained' : IDL.Nat,
    'wear' : IDL.Nat,
    'steps' : IDL.Nat,
    'style' : IDL.Text,
    'performance' : IDL.Nat,
    'brand' : IDL.Text,
  });
  const ShoeCategory = IDL.Variant({
    'sneakers' : IDL.Null,
    'customDesigns' : IDL.Null,
    'sportsShoes' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ShoeProduct = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'style' : IDL.Text,
    'details' : IDL.Text,
    'category' : ShoeCategory,
    'brand' : IDL.Text,
    'image' : ExternalBlob,
    'isNFT' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NFT = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'metadata' : IDL.Text,
    'name' : IDL.Text,
    'image' : ExternalBlob,
  });
  const AirIntegrationSettings = IDL.Record({
    'enabledOledSync' : IDL.Bool,
    'enabledShoeHealth' : IDL.Bool,
    'enabledShoeMusic' : IDL.Bool,
  });
  const AudioUsageContext = IDL.Variant({
    'soundEffect' : IDL.Null,
    'vrExperience' : IDL.Null,
    'other' : IDL.Null,
    'post' : IDL.Null,
    'narration' : IDL.Null,
    'xrExperience' : IDL.Null,
    'ambientSound' : IDL.Null,
    'backgroundMusic' : IDL.Null,
    'avatar' : IDL.Null,
  });
  const AudioType = IDL.Variant({
    'ambient' : IDL.Null,
    'music' : IDL.Null,
    'soundEffect' : IDL.Null,
    'voiceRecording' : IDL.Null,
    'other' : IDL.Null,
    'podcast' : IDL.Null,
    'audiobook' : IDL.Null,
  });
  const AudioAttachment = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'usageContext' : AudioUsageContext,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'audioFile' : ExternalBlob,
    'audioType' : AudioType,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const ChatThread = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'messages' : IDL.Vec(Message),
    'lastMessage' : IDL.Opt(Message),
  });
  const VRExperience = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'audioAttachments' : IDL.Vec(AudioAttachment),
    'image' : IDL.Opt(ExternalBlob),
  });
  const PortfolioContent = IDL.Record({
    'vrExperiences' : IDL.Vec(VRExperience),
    'nfts' : IDL.Vec(NFT),
    'posts' : IDL.Vec(Post),
  });
  const DashboardMetrics = IDL.Record({
    'revenue' : IDL.Nat,
    'engagementRate' : IDL.Nat,
    'salesPerformance' : IDL.Nat,
    'followers' : IDL.Nat,
  });
  const PublicUserProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Theme = IDL.Variant({
    'dark' : IDL.Null,
    'neon' : IDL.Null,
    'light' : IDL.Null,
  });
  const DashboardLayout = IDL.Record({
    'analyticsSection' : IDL.Text,
    'postSection' : IDL.Text,
    'nftSection' : IDL.Text,
    'vrSection' : IDL.Text,
  });
  const MonetizationConfig = IDL.Record({
    'theme' : Theme,
    'exclusiveContentEnabled' : IDL.Bool,
    'tipsEnabled' : IDL.Bool,
    'nftDropsEnabled' : IDL.Bool,
    'dashboardLayout' : DashboardLayout,
  });
  const CreatorMonetizationDashboard = IDL.Record({
    'content' : PortfolioContent,
    'metrics' : DashboardMetrics,
    'userProfile' : PublicUserProfile,
    'config' : MonetizationConfig,
  });
  const DesignFileType = IDL.Variant({
    'image2D' : IDL.Null,
    'model3D' : IDL.Null,
  });
  const DesignFile = IDL.Record({
    'id' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'blob' : ExternalBlob,
    'fileType' : DesignFileType,
  });
  const DesignCustomization = IDL.Record({
    'effects' : IDL.Vec(IDL.Text),
    'patterns' : IDL.Vec(IDL.Text),
    'textures' : IDL.Vec(IDL.Text),
    'colors' : IDL.Vec(IDL.Text),
  });
  const ShoeDesignProject = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'designFiles' : IDL.Vec(DesignFile),
    'customization' : DesignCustomization,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const FriendRequest = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'status' : RequestStatus,
    'from' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const LiveEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'thumbnail' : IDL.Opt(ExternalBlob),
    'votes' : IDL.Nat,
    'hostName' : IDL.Text,
    'host' : IDL.Principal,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'participantCount' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'liveEvent' : IDL.Null,
    'like' : IDL.Null,
    'shoeHealthAlert' : IDL.Null,
    'comment' : IDL.Null,
    'nftDrop' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'notificationType' : NotificationType,
    'user' : IDL.Principal,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const OLEDSettings = IDL.Record({
    'bluetoothPaired' : IDL.Bool,
    'displayMode' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Nat], [], []),
    'addOrUpdateShoeHealth' : IDL.Func([ShoeHealth], [], []),
    'addShoeProduct' : IDL.Func([ShoeProduct], [], []),
    'addShoeStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatThread' : IDL.Func([IDL.Vec(IDL.Principal)], [IDL.Nat], []),
    'createDesignProject' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createLiveEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'createNFT' : IDL.Func([NFT], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [IDL.Nat], []),
    'createPostWithAudio' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteAudioAttachment' : IDL.Func([IDL.Text], [], []),
    'deleteDesignProject' : IDL.Func([IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAirIntegrationSettings' : IDL.Func(
        [IDL.Text],
        [AirIntegrationSettings],
        ['query'],
      ),
    'getAllAudioAttachments' : IDL.Func(
        [],
        [IDL.Vec(AudioAttachment)],
        ['query'],
      ),
    'getAllPostsAudioIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getAllShoeProducts' : IDL.Func([], [IDL.Vec(ShoeProduct)], ['query']),
    'getAudioAttachment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AudioAttachment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatThreads' : IDL.Func([], [IDL.Vec(ChatThread)], ['query']),
    'getCreatorDashboard' : IDL.Func(
        [],
        [IDL.Opt(CreatorMonetizationDashboard)],
        ['query'],
      ),
    'getDesignProject' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ShoeDesignProject)],
        ['query'],
      ),
    'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
    'getLiveEvents' : IDL.Func([], [IDL.Vec(LiveEvent)], ['query']),
    'getMonetizationConfig' : IDL.Func(
        [],
        [IDL.Opt(MonetizationConfig)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOLEDSettings' : IDL.Func([], [IDL.Opt(OLEDSettings)], ['query']),
    'getPostAudioIds' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getShoeProduct' : IDL.Func([IDL.Text], [IDL.Opt(ShoeProduct)], ['query']),
    'getShoeProductsByCategory' : IDL.Func(
        [ShoeCategory],
        [IDL.Vec(ShoeProduct)],
        ['query'],
      ),
    'getShoeStockCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserDesignProjects' : IDL.Func(
        [],
        [IDL.Vec(ShoeDesignProject)],
        ['query'],
      ),
    'getUserNFTs' : IDL.Func([IDL.Principal], [IDL.Vec(NFT)], ['query']),
    'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserShoeHealth' : IDL.Func([], [IDL.Vec(ShoeHealth)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinLiveEvent' : IDL.Func([IDL.Nat], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'rejectFriendRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMonetizationConfig' : IDL.Func([MonetizationConfig], [], []),
    'saveOLEDSettings' : IDL.Func([OLEDSettings], [], []),
    'searchShoeProducts' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Principal)],
        [IDL.Vec(ShoeProduct)],
        ['query'],
      ),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'updateAirIntegrationSettings' : IDL.Func(
        [IDL.Text, AirIntegrationSettings],
        [],
        [],
      ),
    'updateDesignCustomization' : IDL.Func(
        [IDL.Text, DesignCustomization],
        [],
        [],
      ),
    'uploadAudioAttachment' : IDL.Func([AudioAttachment], [], []),
    'uploadDesignFile' : IDL.Func(
        [IDL.Text, DesignFileType, ExternalBlob, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };