/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AirIntegrationSettings {
  'enabledOledSync' : boolean,
  'enabledShoeHealth' : boolean,
  'enabledShoeMusic' : boolean,
}
export interface AudioAttachment {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'usageContext' : AudioUsageContext,
  'owner' : Principal,
  'description' : string,
  'audioFile' : ExternalBlob,
  'audioType' : AudioType,
}
export type AudioType = { 'ambient' : null } |
  { 'music' : null } |
  { 'soundEffect' : null } |
  { 'voiceRecording' : null } |
  { 'other' : null } |
  { 'podcast' : null } |
  { 'audiobook' : null };
export type AudioUsageContext = { 'soundEffect' : null } |
  { 'vrExperience' : null } |
  { 'other' : null } |
  { 'post' : null } |
  { 'narration' : null } |
  { 'xrExperience' : null } |
  { 'ambientSound' : null } |
  { 'backgroundMusic' : null } |
  { 'avatar' : null };
export interface ChatThread {
  'id' : bigint,
  'participants' : Array<Principal>,
  'messages' : Array<Message>,
  'lastMessage' : [] | [Message],
}
export interface CreatorMonetizationDashboard {
  'content' : PortfolioContent,
  'metrics' : DashboardMetrics,
  'userProfile' : PublicUserProfile,
  'config' : MonetizationConfig,
}
export interface DashboardLayout {
  'analyticsSection' : string,
  'postSection' : string,
  'nftSection' : string,
  'vrSection' : string,
}
export interface DashboardMetrics {
  'revenue' : bigint,
  'engagementRate' : bigint,
  'salesPerformance' : bigint,
  'followers' : bigint,
}
export interface DesignCustomization {
  'effects' : Array<string>,
  'patterns' : Array<string>,
  'textures' : Array<string>,
  'colors' : Array<string>,
}
export interface DesignFile {
  'id' : string,
  'thumbnail' : [] | [ExternalBlob],
  'blob' : ExternalBlob,
  'fileType' : DesignFileType,
}
export type DesignFileType = { 'image2D' : null } |
  { 'model3D' : null };
export type ExternalBlob = Uint8Array;
export interface FriendRequest {
  'id' : bigint,
  'to' : Principal,
  'status' : RequestStatus,
  'from' : Principal,
  'timestamp' : bigint,
}
export interface LiveEvent {
  'id' : bigint,
  'title' : string,
  'participants' : Array<Principal>,
  'thumbnail' : [] | [ExternalBlob],
  'votes' : bigint,
  'hostName' : string,
  'host' : Principal,
  'description' : string,
  'isActive' : boolean,
  'participantCount' : bigint,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface MonetizationConfig {
  'theme' : Theme,
  'exclusiveContentEnabled' : boolean,
  'tipsEnabled' : boolean,
  'nftDropsEnabled' : boolean,
  'dashboardLayout' : DashboardLayout,
}
export interface NFT {
  'id' : string,
  'owner' : Principal,
  'metadata' : string,
  'name' : string,
  'image' : ExternalBlob,
}
export interface Notification {
  'id' : bigint,
  'content' : string,
  'notificationType' : NotificationType,
  'user' : Principal,
  'isRead' : boolean,
  'timestamp' : bigint,
}
export type NotificationType = { 'liveEvent' : null } |
  { 'like' : null } |
  { 'shoeHealthAlert' : null } |
  { 'comment' : null } |
  { 'nftDrop' : null };
export interface OLEDSettings {
  'bluetoothPaired' : boolean,
  'displayMode' : string,
  'enabled' : boolean,
}
export interface PortfolioContent {
  'vrExperiences' : Array<VRExperience>,
  'nfts' : Array<NFT>,
  'posts' : Array<Post>,
}
export interface Post {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'audioAttachments' : Array<AudioAttachment>,
  'image' : [] | [ExternalBlob],
}
export interface PublicUserProfile {
  'id' : string,
  'bio' : string,
  'username' : string,
  'avatar' : [] | [ExternalBlob],
}
export type RequestStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type ShoeCategory = { 'sneakers' : null } |
  { 'customDesigns' : null } |
  { 'sportsShoes' : null };
export interface ShoeDesignProject {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'designFiles' : Array<DesignFile>,
  'customization' : DesignCustomization,
}
export interface ShoeHealth {
  'id' : string,
  'lastMaintained' : bigint,
  'wear' : bigint,
  'steps' : bigint,
  'style' : string,
  'performance' : bigint,
  'brand' : string,
}
export interface ShoeProduct {
  'id' : string,
  'creator' : Principal,
  'style' : string,
  'details' : string,
  'category' : ShoeCategory,
  'brand' : string,
  'image' : ExternalBlob,
  'isNFT' : boolean,
  'price' : bigint,
}
export type Theme = { 'dark' : null } |
  { 'neon' : null } |
  { 'light' : null };
export interface UserProfile {
  'id' : string,
  'bio' : string,
  'username' : string,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VRExperience {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'description' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[bigint], undefined>,
  'addOrUpdateShoeHealth' : ActorMethod<[ShoeHealth], undefined>,
  'addShoeProduct' : ActorMethod<[ShoeProduct], undefined>,
  'addShoeStock' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatThread' : ActorMethod<[Array<Principal>], bigint>,
  'createDesignProject' : ActorMethod<[string], string>,
  'createLiveEvent' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'createNFT' : ActorMethod<[NFT], undefined>,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], bigint>,
  'createPostWithAudio' : ActorMethod<
    [string, [] | [ExternalBlob], Array<string>],
    bigint
  >,
  'deleteAudioAttachment' : ActorMethod<[string], undefined>,
  'deleteDesignProject' : ActorMethod<[string], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAirIntegrationSettings' : ActorMethod<[string], AirIntegrationSettings>,
  'getAllAudioAttachments' : ActorMethod<[], Array<AudioAttachment>>,
  'getAllPostsAudioIds' : ActorMethod<[], Array<[bigint, Array<string>]>>,
  'getAllShoeProducts' : ActorMethod<[], Array<ShoeProduct>>,
  'getAudioAttachment' : ActorMethod<[string], [] | [AudioAttachment]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatThreads' : ActorMethod<[], Array<ChatThread>>,
  'getCreatorDashboard' : ActorMethod<[], [] | [CreatorMonetizationDashboard]>,
  'getDesignProject' : ActorMethod<[string], [] | [ShoeDesignProject]>,
  'getFollowerCount' : ActorMethod<[Principal], bigint>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFriendRequests' : ActorMethod<[], Array<FriendRequest>>,
  'getLiveEvents' : ActorMethod<[], Array<LiveEvent>>,
  'getMonetizationConfig' : ActorMethod<[], [] | [MonetizationConfig]>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getOLEDSettings' : ActorMethod<[], [] | [OLEDSettings]>,
  'getPostAudioIds' : ActorMethod<[bigint], Array<string>>,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getShoeProduct' : ActorMethod<[string], [] | [ShoeProduct]>,
  'getShoeProductsByCategory' : ActorMethod<[ShoeCategory], Array<ShoeProduct>>,
  'getShoeStockCount' : ActorMethod<[string], bigint>,
  'getUserDesignProjects' : ActorMethod<[], Array<ShoeDesignProject>>,
  'getUserNFTs' : ActorMethod<[Principal], Array<NFT>>,
  'getUserPosts' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserShoeHealth' : ActorMethod<[], Array<ShoeHealth>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinLiveEvent' : ActorMethod<[bigint], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'rejectFriendRequest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMonetizationConfig' : ActorMethod<[MonetizationConfig], undefined>,
  'saveOLEDSettings' : ActorMethod<[OLEDSettings], undefined>,
  'searchShoeProducts' : ActorMethod<
    [string, [] | [Principal]],
    Array<ShoeProduct>
  >,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'updateAirIntegrationSettings' : ActorMethod<
    [string, AirIntegrationSettings],
    undefined
  >,
  'updateDesignCustomization' : ActorMethod<
    [string, DesignCustomization],
    undefined
  >,
  'uploadAudioAttachment' : ActorMethod<[AudioAttachment], undefined>,
  'uploadDesignFile' : ActorMethod<
    [string, DesignFileType, ExternalBlob, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];