/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    id: string;
    bio: string;
    username: string;
    avatar?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PortfolioContent {
    vrExperiences: Array<VRExperience>;
    nfts: Array<NFT>;
    posts: Array<Post>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface NFT {
    id: string;
    owner: Principal;
    metadata: string;
    name: string;
    image: ExternalBlob;
}
export interface OLEDSettings {
    bluetoothPaired: boolean;
    displayMode: string;
    enabled: boolean;
}
export interface FriendRequest {
    id: bigint;
    to: Principal;
    status: RequestStatus;
    from: Principal;
    timestamp: bigint;
}
export interface PublicUserProfile {
    id: string;
    bio: string;
    username: string;
    avatar?: ExternalBlob;
}
export interface ChatThread {
    id: bigint;
    participants: Array<Principal>;
    messages: Array<Message>;
    lastMessage?: Message;
}
export interface Post {
    id: bigint;
    content: string;
    author: Principal;
    audioAttachments: Array<AudioAttachment>;
    image?: ExternalBlob;
}
export interface LiveEvent {
    id: bigint;
    title: string;
    participants: Array<Principal>;
    thumbnail?: ExternalBlob;
    votes: bigint;
    hostName: string;
    host: Principal;
    description: string;
    isActive: boolean;
    participantCount: bigint;
}
export interface AirIntegrationSettings {
    enabledOledSync: boolean;
    enabledShoeHealth: boolean;
    enabledShoeMusic: boolean;
}
export interface ShoeHealth {
    id: string;
    lastMaintained: bigint;
    wear: bigint;
    steps: bigint;
    style: string;
    performance: bigint;
    brand: string;
}
export interface ShoeDesignProject {
    id: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    designFiles: Array<DesignFile>;
    customization: DesignCustomization;
}
export interface ShoeProduct {
    id: string;
    creator: Principal;
    style: string;
    details: string;
    category: ShoeCategory;
    brand: string;
    image: ExternalBlob;
    isNFT: boolean;
    price: bigint;
}
export interface DesignCustomization {
    effects: Array<string>;
    patterns: Array<string>;
    textures: Array<string>;
    colors: Array<string>;
}
export interface MonetizationConfig {
    theme: Theme;
    exclusiveContentEnabled: boolean;
    tipsEnabled: boolean;
    nftDropsEnabled: boolean;
    dashboardLayout: DashboardLayout;
}
export interface DashboardLayout {
    analyticsSection: string;
    postSection: string;
    nftSection: string;
    vrSection: string;
}
export interface VRExperience {
    id: string;
    title: string;
    owner: Principal;
    description: string;
}
export interface Notification {
    id: bigint;
    content: string;
    notificationType: NotificationType;
    user: Principal;
    isRead: boolean;
    timestamp: bigint;
}
export interface AudioAttachment {
    id: string;
    title: string;
    duration: bigint;
    usageContext: AudioUsageContext;
    owner: Principal;
    description: string;
    audioFile: ExternalBlob;
    audioType: AudioType;
}
export interface Message {
    id: bigint;
    content: string;
    sender: Principal;
    timestamp: bigint;
}
export interface DashboardMetrics {
    revenue: bigint;
    engagementRate: bigint;
    salesPerformance: bigint;
    followers: bigint;
}
export interface CreatorMonetizationDashboard {
    content: PortfolioContent;
    metrics: DashboardMetrics;
    userProfile: PublicUserProfile;
    config: MonetizationConfig;
}
export interface DesignFile {
    id: string;
    thumbnail?: ExternalBlob;
    blob: ExternalBlob;
    fileType: DesignFileType;
}
export enum AudioType {
    ambient = "ambient",
    music = "music",
    soundEffect = "soundEffect",
    voiceRecording = "voiceRecording",
    other = "other",
    podcast = "podcast",
    audiobook = "audiobook"
}
export enum AudioUsageContext {
    soundEffect = "soundEffect",
    vrExperience = "vrExperience",
    other = "other",
    post = "post",
    narration = "narration",
    xrExperience = "xrExperience",
    ambientSound = "ambientSound",
    backgroundMusic = "backgroundMusic",
    avatar = "avatar"
}
export enum DesignFileType {
    image2D = "image2D",
    model3D = "model3D"
}
export enum NotificationType {
    liveEvent = "liveEvent",
    like = "like",
    shoeHealthAlert = "shoeHealthAlert",
    comment = "comment",
    nftDrop = "nftDrop"
}
export enum RequestStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum ShoeCategory {
    sneakers = "sneakers",
    customDesigns = "customDesigns",
    sportsShoes = "sportsShoes"
}
export enum Theme {
    dark = "dark",
    neon = "neon",
    light = "light"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptFriendRequest(requestId: bigint): Promise<void>;
    addOrUpdateShoeHealth(shoe: ShoeHealth): Promise<void>;
    addShoeProduct(product: ShoeProduct): Promise<void>;
    addShoeStock(id: string, quantity: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChatThread(participants: Array<Principal>): Promise<bigint>;
    createDesignProject(name: string): Promise<string>;
    createLiveEvent(title: string, hostName: string, description: string, thumbnail: ExternalBlob | null): Promise<bigint>;
    createNFT(nft: NFT): Promise<void>;
    createPost(content: string, image: ExternalBlob | null): Promise<bigint>;
    createPostWithAudio(content: string, image: ExternalBlob | null, audioIds: Array<string>): Promise<bigint>;
    deleteAudioAttachment(id: string): Promise<void>;
    deleteDesignProject(projectId: string): Promise<void>;
    followUser(user: Principal): Promise<void>;
    getAirIntegrationSettings(nftId: string): Promise<AirIntegrationSettings>;
    getAllAudioAttachments(): Promise<Array<AudioAttachment>>;
    getAllPostsAudioIds(): Promise<Array<[bigint, Array<string>]>>;
    getAllShoeProducts(): Promise<Array<ShoeProduct>>;
    getAudioAttachment(id: string): Promise<AudioAttachment | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatThreads(): Promise<Array<ChatThread>>;
    getCreatorDashboard(): Promise<CreatorMonetizationDashboard | null>;
    getDesignProject(projectId: string): Promise<ShoeDesignProject | null>;
    getFollowerCount(user: Principal): Promise<bigint>;
    getFollowers(user: Principal): Promise<Array<Principal>>;
    getFriendRequests(): Promise<Array<FriendRequest>>;
    getLiveEvents(): Promise<Array<LiveEvent>>;
    getMonetizationConfig(): Promise<MonetizationConfig | null>;
    getNotifications(): Promise<Array<Notification>>;
    getOLEDSettings(): Promise<OLEDSettings | null>;
    getPostAudioIds(postId: bigint): Promise<Array<string>>;
    getPosts(): Promise<Array<Post>>;
    getShoeProduct(id: string): Promise<ShoeProduct | null>;
    getShoeProductsByCategory(category: ShoeCategory): Promise<Array<ShoeProduct>>;
    getShoeStockCount(id: string): Promise<bigint>;
    getUserDesignProjects(): Promise<Array<ShoeDesignProject>>;
    getUserNFTs(user: Principal): Promise<Array<NFT>>;
    getUserPosts(user: Principal): Promise<Array<Post>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserShoeHealth(): Promise<Array<ShoeHealth>>;
    isCallerAdmin(): Promise<boolean>;
    joinLiveEvent(eventId: bigint): Promise<void>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    rejectFriendRequest(requestId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMonetizationConfig(config: MonetizationConfig): Promise<void>;
    saveOLEDSettings(settings: OLEDSettings): Promise<void>;
    searchShoeProducts(brand: string, creator: Principal | null): Promise<Array<ShoeProduct>>;
    sendFriendRequest(to: Principal): Promise<void>;
    sendMessage(threadId: bigint, content: string): Promise<void>;
    unfollowUser(user: Principal): Promise<void>;
    updateAirIntegrationSettings(nftId: string, settings: AirIntegrationSettings): Promise<void>;
    updateDesignCustomization(projectId: string, customization: DesignCustomization): Promise<void>;
    uploadAudioAttachment(audio: AudioAttachment): Promise<void>;
    uploadDesignFile(projectId: string, fileType: DesignFileType, blob: ExternalBlob, thumbnail: ExternalBlob | null): Promise<void>;
}
import type { AudioAttachment as _AudioAttachment, AudioType as _AudioType, AudioUsageContext as _AudioUsageContext, ChatThread as _ChatThread, CreatorMonetizationDashboard as _CreatorMonetizationDashboard, DashboardLayout as _DashboardLayout, DashboardMetrics as _DashboardMetrics, DesignCustomization as _DesignCustomization, DesignFile as _DesignFile, DesignFileType as _DesignFileType, ExternalBlob as _ExternalBlob, FriendRequest as _FriendRequest, LiveEvent as _LiveEvent, Message as _Message, MonetizationConfig as _MonetizationConfig, NFT as _NFT, Notification as _Notification, NotificationType as _NotificationType, OLEDSettings as _OLEDSettings, PortfolioContent as _PortfolioContent, Post as _Post, PublicUserProfile as _PublicUserProfile, RequestStatus as _RequestStatus, ShoeCategory as _ShoeCategory, ShoeDesignProject as _ShoeDesignProject, ShoeProduct as _ShoeProduct, Theme as _Theme, UserProfile as _UserProfile, UserRole as _UserRole, VRExperience as _VRExperience, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptFriendRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async addOrUpdateShoeHealth(arg0: ShoeHealth): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateShoeHealth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateShoeHealth(arg0);
            return result;
        }
    }
    async addShoeProduct(arg0: ShoeProduct): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShoeProduct(await to_candid_ShoeProduct_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShoeProduct(await to_candid_ShoeProduct_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addShoeStock(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShoeStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShoeStock(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChatThread(arg0: Array<Principal>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatThread(arg0);
            return result;
        }
    }
    async createDesignProject(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDesignProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDesignProject(arg0);
            return result;
        }
    }
    async createLiveEvent(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLiveEvent(arg0, arg1, arg2, await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLiveEvent(arg0, arg1, arg2, await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createNFT(arg0: NFT): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNFT(await to_candid_NFT_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNFT(await to_candid_NFT_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPost(arg0: string, arg1: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPostWithAudio(arg0: string, arg1: ExternalBlob | null, arg2: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPostWithAudio(arg0, await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPostWithAudio(arg0, await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async deleteAudioAttachment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAudioAttachment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAudioAttachment(arg0);
            return result;
        }
    }
    async deleteDesignProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDesignProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDesignProject(arg0);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getAirIntegrationSettings(arg0: string): Promise<AirIntegrationSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAirIntegrationSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAirIntegrationSettings(arg0);
            return result;
        }
    }
    async getAllAudioAttachments(): Promise<Array<AudioAttachment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAudioAttachments();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAudioAttachments();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPostsAudioIds(): Promise<Array<[bigint, Array<string>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPostsAudioIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPostsAudioIds();
            return result;
        }
    }
    async getAllShoeProducts(): Promise<Array<ShoeProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShoeProducts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShoeProducts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAudioAttachment(arg0: string): Promise<AudioAttachment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudioAttachment(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudioAttachment(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatThreads(): Promise<Array<ChatThread>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatThreads();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatThreads();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatorDashboard(): Promise<CreatorMonetizationDashboard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorDashboard();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorDashboard();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesignProject(arg0: string): Promise<ShoeDesignProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesignProject(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesignProject(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowerCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowerCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowerCount(arg0);
            return result;
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFriendRequests(): Promise<Array<FriendRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequests();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequests();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiveEvents(): Promise<Array<LiveEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveEvents();
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveEvents();
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonetizationConfig(): Promise<MonetizationConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonetizationConfig();
                return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonetizationConfig();
            return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOLEDSettings(): Promise<OLEDSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOLEDSettings();
                return from_candid_opt_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOLEDSettings();
            return from_candid_opt_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostAudioIds(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostAudioIds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostAudioIds(arg0);
            return result;
        }
    }
    async getPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShoeProduct(arg0: string): Promise<ShoeProduct | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoeProduct(arg0);
                return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoeProduct(arg0);
            return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShoeProductsByCategory(arg0: ShoeCategory): Promise<Array<ShoeProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoeProductsByCategory(to_candid_ShoeCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoeProductsByCategory(to_candid_ShoeCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShoeStockCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoeStockCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoeStockCount(arg0);
            return result;
        }
    }
    async getUserDesignProjects(): Promise<Array<ShoeDesignProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDesignProjects();
                return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDesignProjects();
            return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserNFTs(arg0: Principal): Promise<Array<NFT>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNFTs(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNFTs(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPosts(arg0: Principal): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPosts(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPosts(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserShoeHealth(): Promise<Array<ShoeHealth>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserShoeHealth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserShoeHealth();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinLiveEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinLiveEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinLiveEvent(arg0);
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async rejectFriendRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFriendRequest(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n83(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n83(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMonetizationConfig(arg0: MonetizationConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMonetizationConfig(to_candid_MonetizationConfig_n85(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMonetizationConfig(to_candid_MonetizationConfig_n85(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveOLEDSettings(arg0: OLEDSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOLEDSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOLEDSettings(arg0);
            return result;
        }
    }
    async searchShoeProducts(arg0: string, arg1: Principal | null): Promise<Array<ShoeProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchShoeProducts(arg0, to_candid_opt_n89(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchShoeProducts(arg0, to_candid_opt_n89(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async sendMessage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async updateAirIntegrationSettings(arg0: string, arg1: AirIntegrationSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAirIntegrationSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAirIntegrationSettings(arg0, arg1);
            return result;
        }
    }
    async updateDesignCustomization(arg0: string, arg1: DesignCustomization): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDesignCustomization(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDesignCustomization(arg0, arg1);
            return result;
        }
    }
    async uploadAudioAttachment(arg0: AudioAttachment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAudioAttachment(await to_candid_AudioAttachment_n90(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAudioAttachment(await to_candid_AudioAttachment_n90(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadDesignFile(arg0: string, arg1: DesignFileType, arg2: ExternalBlob, arg3: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDesignFile(arg0, to_candid_DesignFileType_n96(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDesignFile(arg0, to_candid_DesignFileType_n96(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
async function from_candid_AudioAttachment_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioAttachment): Promise<AudioAttachment> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_AudioType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioType): AudioType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_AudioUsageContext_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioUsageContext): AudioUsageContext {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ChatThread_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatThread): ChatThread {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_CreatorMonetizationDashboard_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatorMonetizationDashboard): Promise<CreatorMonetizationDashboard> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_DesignFileType_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignFileType): DesignFileType {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
async function from_candid_DesignFile_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignFile): Promise<DesignFile> {
    return await from_candid_record_n63(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FriendRequest_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequest): FriendRequest {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
async function from_candid_LiveEvent_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveEvent): Promise<LiveEvent> {
    return await from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_MonetizationConfig_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MonetizationConfig): MonetizationConfig {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
async function from_candid_NFT_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFT): Promise<NFT> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n79(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n77(_uploadFile, _downloadFile, value);
}
async function from_candid_PortfolioContent_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioContent): Promise<PortfolioContent> {
    return await from_candid_record_n46(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
async function from_candid_PublicUserProfile_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicUserProfile): Promise<PublicUserProfile> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_ShoeCategory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShoeCategory): ShoeCategory {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ShoeDesignProject_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShoeDesignProject): Promise<ShoeDesignProject> {
    return await from_candid_record_n60(_uploadFile, _downloadFile, value);
}
async function from_candid_ShoeProduct_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShoeProduct): Promise<ShoeProduct> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Theme_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AudioAttachment]): Promise<AudioAttachment | null> {
    return value.length === 0 ? null : await from_candid_AudioAttachment_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CreatorMonetizationDashboard]): Promise<CreatorMonetizationDashboard | null> {
    return value.length === 0 ? null : await from_candid_CreatorMonetizationDashboard_n43(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShoeDesignProject]): Promise<ShoeDesignProject | null> {
    return value.length === 0 ? null : await from_candid_ShoeDesignProject_n59(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonetizationConfig]): MonetizationConfig | null {
    return value.length === 0 ? null : from_candid_MonetizationConfig_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OLEDSettings]): OLEDSettings | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShoeProduct]): Promise<ShoeProduct | null> {
    return value.length === 0 ? null : await from_candid_ShoeProduct_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: bigint;
    usageContext: _AudioUsageContext;
    owner: Principal;
    description: string;
    audioFile: _ExternalBlob;
    audioType: _AudioType;
}): Promise<{
    id: string;
    title: string;
    duration: bigint;
    usageContext: AudioUsageContext;
    owner: Principal;
    description: string;
    audioFile: ExternalBlob;
    audioType: AudioType;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        usageContext: from_candid_AudioUsageContext_n21(_uploadFile, _downloadFile, value.usageContext),
        owner: value.owner,
        description: value.description,
        audioFile: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.audioFile),
        audioType: from_candid_AudioType_n24(_uploadFile, _downloadFile, value.audioType)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: Principal;
    style: string;
    details: string;
    category: _ShoeCategory;
    brand: string;
    image: _ExternalBlob;
    isNFT: boolean;
    price: bigint;
}): Promise<{
    id: string;
    creator: Principal;
    style: string;
    details: string;
    category: ShoeCategory;
    brand: string;
    image: ExternalBlob;
    isNFT: boolean;
    price: bigint;
}> {
    return {
        id: value.id,
        creator: value.creator,
        style: value.style,
        details: value.details,
        category: from_candid_ShoeCategory_n29(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        image: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.image),
        isNFT: value.isNFT,
        price: value.price
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    username: string;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    bio: string;
    username: string;
    avatar?: ExternalBlob;
}> {
    return {
        id: value.id,
        bio: value.bio,
        username: value.username,
        avatar: record_opt_to_undefined(await from_candid_opt_n35(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    participants: Array<Principal>;
    messages: Array<_Message>;
    lastMessage: [] | [_Message];
}): {
    id: bigint;
    participants: Array<Principal>;
    messages: Array<Message>;
    lastMessage?: Message;
} {
    return {
        id: value.id,
        participants: value.participants,
        messages: value.messages,
        lastMessage: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.lastMessage))
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: _PortfolioContent;
    metrics: _DashboardMetrics;
    userProfile: _PublicUserProfile;
    config: _MonetizationConfig;
}): Promise<{
    content: PortfolioContent;
    metrics: DashboardMetrics;
    userProfile: PublicUserProfile;
    config: MonetizationConfig;
}> {
    return {
        content: await from_candid_PortfolioContent_n45(_uploadFile, _downloadFile, value.content),
        metrics: value.metrics,
        userProfile: await from_candid_PublicUserProfile_n53(_uploadFile, _downloadFile, value.userProfile),
        config: from_candid_MonetizationConfig_n54(_uploadFile, _downloadFile, value.config)
    };
}
async function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vrExperiences: Array<_VRExperience>;
    nfts: Array<_NFT>;
    posts: Array<_Post>;
}): Promise<{
    vrExperiences: Array<VRExperience>;
    nfts: Array<NFT>;
    posts: Array<Post>;
}> {
    return {
        vrExperiences: value.vrExperiences,
        nfts: await from_candid_vec_n47(_uploadFile, _downloadFile, value.nfts),
        posts: await from_candid_vec_n50(_uploadFile, _downloadFile, value.posts)
    };
}
async function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    metadata: string;
    name: string;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    owner: Principal;
    metadata: string;
    name: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        owner: value.owner,
        metadata: value.metadata,
        name: value.name,
        image: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    author: Principal;
    audioAttachments: Array<_AudioAttachment>;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    content: string;
    author: Principal;
    audioAttachments: Array<AudioAttachment>;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        content: value.content,
        author: value.author,
        audioAttachments: await from_candid_vec_n18(_uploadFile, _downloadFile, value.audioAttachments),
        image: record_opt_to_undefined(await from_candid_opt_n35(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: _Theme;
    exclusiveContentEnabled: boolean;
    tipsEnabled: boolean;
    nftDropsEnabled: boolean;
    dashboardLayout: _DashboardLayout;
}): {
    theme: Theme;
    exclusiveContentEnabled: boolean;
    tipsEnabled: boolean;
    nftDropsEnabled: boolean;
    dashboardLayout: DashboardLayout;
} {
    return {
        theme: from_candid_Theme_n56(_uploadFile, _downloadFile, value.theme),
        exclusiveContentEnabled: value.exclusiveContentEnabled,
        tipsEnabled: value.tipsEnabled,
        nftDropsEnabled: value.nftDropsEnabled,
        dashboardLayout: value.dashboardLayout
    };
}
async function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    designFiles: Array<_DesignFile>;
    customization: _DesignCustomization;
}): Promise<{
    id: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    designFiles: Array<DesignFile>;
    customization: DesignCustomization;
}> {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        designFiles: await from_candid_vec_n61(_uploadFile, _downloadFile, value.designFiles),
        customization: value.customization
    };
}
async function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    thumbnail: [] | [_ExternalBlob];
    blob: _ExternalBlob;
    fileType: _DesignFileType;
}): Promise<{
    id: string;
    thumbnail?: ExternalBlob;
    blob: ExternalBlob;
    fileType: DesignFileType;
}> {
    return {
        id: value.id,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n35(_uploadFile, _downloadFile, value.thumbnail)),
        blob: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.blob),
        fileType: from_candid_DesignFileType_n64(_uploadFile, _downloadFile, value.fileType)
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: Principal;
    status: _RequestStatus;
    from: Principal;
    timestamp: bigint;
}): {
    id: bigint;
    to: Principal;
    status: RequestStatus;
    from: Principal;
    timestamp: bigint;
} {
    return {
        id: value.id,
        to: value.to,
        status: from_candid_RequestStatus_n69(_uploadFile, _downloadFile, value.status),
        from: value.from,
        timestamp: value.timestamp
    };
}
async function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    participants: Array<Principal>;
    thumbnail: [] | [_ExternalBlob];
    votes: bigint;
    hostName: string;
    host: Principal;
    description: string;
    isActive: boolean;
    participantCount: bigint;
}): Promise<{
    id: bigint;
    title: string;
    participants: Array<Principal>;
    thumbnail?: ExternalBlob;
    votes: bigint;
    hostName: string;
    host: Principal;
    description: string;
    isActive: boolean;
    participantCount: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        participants: value.participants,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n35(_uploadFile, _downloadFile, value.thumbnail)),
        votes: value.votes,
        hostName: value.hostName,
        host: value.host,
        description: value.description,
        isActive: value.isActive,
        participantCount: value.participantCount
    };
}
function from_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    notificationType: _NotificationType;
    user: Principal;
    isRead: boolean;
    timestamp: bigint;
}): {
    id: bigint;
    content: string;
    notificationType: NotificationType;
    user: Principal;
    isRead: boolean;
    timestamp: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        notificationType: from_candid_NotificationType_n78(_uploadFile, _downloadFile, value.notificationType),
        user: value.user,
        isRead: value.isRead,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    soundEffect: null;
} | {
    vrExperience: null;
} | {
    other: null;
} | {
    post: null;
} | {
    narration: null;
} | {
    xrExperience: null;
} | {
    ambientSound: null;
} | {
    backgroundMusic: null;
} | {
    avatar: null;
}): AudioUsageContext {
    return "soundEffect" in value ? AudioUsageContext.soundEffect : "vrExperience" in value ? AudioUsageContext.vrExperience : "other" in value ? AudioUsageContext.other : "post" in value ? AudioUsageContext.post : "narration" in value ? AudioUsageContext.narration : "xrExperience" in value ? AudioUsageContext.xrExperience : "ambientSound" in value ? AudioUsageContext.ambientSound : "backgroundMusic" in value ? AudioUsageContext.backgroundMusic : "avatar" in value ? AudioUsageContext.avatar : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ambient: null;
} | {
    music: null;
} | {
    soundEffect: null;
} | {
    voiceRecording: null;
} | {
    other: null;
} | {
    podcast: null;
} | {
    audiobook: null;
}): AudioType {
    return "ambient" in value ? AudioType.ambient : "music" in value ? AudioType.music : "soundEffect" in value ? AudioType.soundEffect : "voiceRecording" in value ? AudioType.voiceRecording : "other" in value ? AudioType.other : "podcast" in value ? AudioType.podcast : "audiobook" in value ? AudioType.audiobook : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sneakers: null;
} | {
    customDesigns: null;
} | {
    sportsShoes: null;
}): ShoeCategory {
    return "sneakers" in value ? ShoeCategory.sneakers : "customDesigns" in value ? ShoeCategory.customDesigns : "sportsShoes" in value ? ShoeCategory.sportsShoes : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dark: null;
} | {
    neon: null;
} | {
    light: null;
}): Theme {
    return "dark" in value ? Theme.dark : "neon" in value ? Theme.neon : "light" in value ? Theme.light : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    image2D: null;
} | {
    model3D: null;
}): DesignFileType {
    return "image2D" in value ? DesignFileType.image2D : "model3D" in value ? DesignFileType.model3D : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "rejected" in value ? RequestStatus.rejected : "accepted" in value ? RequestStatus.accepted : value;
}
function from_candid_variant_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    liveEvent: null;
} | {
    like: null;
} | {
    shoeHealthAlert: null;
} | {
    comment: null;
} | {
    nftDrop: null;
}): NotificationType {
    return "liveEvent" in value ? NotificationType.liveEvent : "like" in value ? NotificationType.like : "shoeHealthAlert" in value ? NotificationType.shoeHealthAlert : "comment" in value ? NotificationType.comment : "nftDrop" in value ? NotificationType.nftDrop : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AudioAttachment>): Promise<Array<AudioAttachment>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AudioAttachment_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShoeProduct>): Promise<Array<ShoeProduct>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ShoeProduct_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatThread>): Array<ChatThread> {
    return value.map((x)=>from_candid_ChatThread_n39(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NFT>): Promise<Array<NFT>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NFT_n48(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n51(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DesignFile>): Promise<Array<DesignFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DesignFile_n62(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendRequest>): Array<FriendRequest> {
    return value.map((x)=>from_candid_FriendRequest_n67(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiveEvent>): Promise<Array<LiveEvent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LiveEvent_n72(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n76(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShoeDesignProject>): Promise<Array<ShoeDesignProject>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ShoeDesignProject_n59(_uploadFile, _downloadFile, x)));
}
async function to_candid_AudioAttachment_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioAttachment): Promise<_AudioAttachment> {
    return await to_candid_record_n91(_uploadFile, _downloadFile, value);
}
function to_candid_AudioType_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioType): _AudioType {
    return to_candid_variant_n95(_uploadFile, _downloadFile, value);
}
function to_candid_AudioUsageContext_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioUsageContext): _AudioUsageContext {
    return to_candid_variant_n93(_uploadFile, _downloadFile, value);
}
function to_candid_DesignFileType_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignFileType): _DesignFileType {
    return to_candid_variant_n97(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MonetizationConfig_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MonetizationConfig): _MonetizationConfig {
    return to_candid_record_n86(_uploadFile, _downloadFile, value);
}
async function to_candid_NFT_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NFT): Promise<_NFT> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ShoeCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShoeCategory): _ShoeCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ShoeProduct_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShoeProduct): Promise<_ShoeProduct> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Theme_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): _Theme {
    return to_candid_variant_n88(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n84(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    metadata: string;
    name: string;
    image: ExternalBlob;
}): Promise<{
    id: string;
    owner: Principal;
    metadata: string;
    name: string;
    image: _ExternalBlob;
}> {
    return {
        id: value.id,
        owner: value.owner,
        metadata: value.metadata,
        name: value.name,
        image: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    username: string;
    avatar?: ExternalBlob;
}): Promise<{
    id: string;
    bio: string;
    username: string;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        bio: value.bio,
        username: value.username,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: Theme;
    exclusiveContentEnabled: boolean;
    tipsEnabled: boolean;
    nftDropsEnabled: boolean;
    dashboardLayout: DashboardLayout;
}): {
    theme: _Theme;
    exclusiveContentEnabled: boolean;
    tipsEnabled: boolean;
    nftDropsEnabled: boolean;
    dashboardLayout: _DashboardLayout;
} {
    return {
        theme: to_candid_Theme_n87(_uploadFile, _downloadFile, value.theme),
        exclusiveContentEnabled: value.exclusiveContentEnabled,
        tipsEnabled: value.tipsEnabled,
        nftDropsEnabled: value.nftDropsEnabled,
        dashboardLayout: value.dashboardLayout
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: Principal;
    style: string;
    details: string;
    category: ShoeCategory;
    brand: string;
    image: ExternalBlob;
    isNFT: boolean;
    price: bigint;
}): Promise<{
    id: string;
    creator: Principal;
    style: string;
    details: string;
    category: _ShoeCategory;
    brand: string;
    image: _ExternalBlob;
    isNFT: boolean;
    price: bigint;
}> {
    return {
        id: value.id,
        creator: value.creator,
        style: value.style,
        details: value.details,
        category: to_candid_ShoeCategory_n10(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        image: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image),
        isNFT: value.isNFT,
        price: value.price
    };
}
async function to_candid_record_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: bigint;
    usageContext: AudioUsageContext;
    owner: Principal;
    description: string;
    audioFile: ExternalBlob;
    audioType: AudioType;
}): Promise<{
    id: string;
    title: string;
    duration: bigint;
    usageContext: _AudioUsageContext;
    owner: Principal;
    description: string;
    audioFile: _ExternalBlob;
    audioType: _AudioType;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        usageContext: to_candid_AudioUsageContext_n92(_uploadFile, _downloadFile, value.usageContext),
        owner: value.owner,
        description: value.description,
        audioFile: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.audioFile),
        audioType: to_candid_AudioType_n94(_uploadFile, _downloadFile, value.audioType)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShoeCategory): {
    sneakers: null;
} | {
    customDesigns: null;
} | {
    sportsShoes: null;
} {
    return value == ShoeCategory.sneakers ? {
        sneakers: null
    } : value == ShoeCategory.customDesigns ? {
        customDesigns: null
    } : value == ShoeCategory.sportsShoes ? {
        sportsShoes: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): {
    dark: null;
} | {
    neon: null;
} | {
    light: null;
} {
    return value == Theme.dark ? {
        dark: null
    } : value == Theme.neon ? {
        neon: null
    } : value == Theme.light ? {
        light: null
    } : value;
}
function to_candid_variant_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioUsageContext): {
    soundEffect: null;
} | {
    vrExperience: null;
} | {
    other: null;
} | {
    post: null;
} | {
    narration: null;
} | {
    xrExperience: null;
} | {
    ambientSound: null;
} | {
    backgroundMusic: null;
} | {
    avatar: null;
} {
    return value == AudioUsageContext.soundEffect ? {
        soundEffect: null
    } : value == AudioUsageContext.vrExperience ? {
        vrExperience: null
    } : value == AudioUsageContext.other ? {
        other: null
    } : value == AudioUsageContext.post ? {
        post: null
    } : value == AudioUsageContext.narration ? {
        narration: null
    } : value == AudioUsageContext.xrExperience ? {
        xrExperience: null
    } : value == AudioUsageContext.ambientSound ? {
        ambientSound: null
    } : value == AudioUsageContext.backgroundMusic ? {
        backgroundMusic: null
    } : value == AudioUsageContext.avatar ? {
        avatar: null
    } : value;
}
function to_candid_variant_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioType): {
    ambient: null;
} | {
    music: null;
} | {
    soundEffect: null;
} | {
    voiceRecording: null;
} | {
    other: null;
} | {
    podcast: null;
} | {
    audiobook: null;
} {
    return value == AudioType.ambient ? {
        ambient: null
    } : value == AudioType.music ? {
        music: null
    } : value == AudioType.soundEffect ? {
        soundEffect: null
    } : value == AudioType.voiceRecording ? {
        voiceRecording: null
    } : value == AudioType.other ? {
        other: null
    } : value == AudioType.podcast ? {
        podcast: null
    } : value == AudioType.audiobook ? {
        audiobook: null
    } : value;
}
function to_candid_variant_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignFileType): {
    image2D: null;
} | {
    model3D: null;
} {
    return value == DesignFileType.image2D ? {
        image2D: null
    } : value == DesignFileType.model3D ? {
        model3D: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
